@Library('jenkins')_

pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                buildMaven()
            }
        }
        stage('Test') {
            steps {
                mvTest()
            }
            post {
                always {
                   ju()
                }
            }
        }
        stage('Deliver') {
            steps {
                deliver()
            }
        }
    }
}
